FROM ajaydivakaran/dw-ubuntu-base:latest

MAINTAINER ajaydivakaran

RUN wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.deb && dpkg -i elasticsearch-0.90.13.deb

EXPOSE 9200

CMD /bin/bash

